/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MindVault */

#ifndef _Included_MindVault
#define _Included_MindVault
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MindVault
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MindVault_init
  (JNIEnv *, jobject);

/*
 * Class:     MindVault
 * Method:    open
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_MindVault_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     MindVault
 * Method:    insert
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_MindVault_insert
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     MindVault
 * Method:    query
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_MindVault_query
  (JNIEnv *, jobject, jint);

/*
 * Class:     MindVault
 * Method:    delete
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_MindVault_delete
  (JNIEnv *, jobject, jint);

/*
 * Class:     MindVault
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MindVault_close
  (JNIEnv *, jobject);

/*
 * Class:     MindVault
 * Method:    status
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MindVault_status
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
